version: '3.8'

services:
  fastapi-app:
    build:
      context: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis-server

  redis-server:
    image: redis:latest
    ports:
      - "6379:6379"
